name: go threagile pipeline

on:
  push:
    branches:
      - feature/*
      - fix/*
      - bugfix/*
      - dependabot/**
      - master
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - id: tag_bump_version
      name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.18.0
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        DRY_RUN: true

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

    - id: gh_release
      name: Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/master'
      with:
        body_path: RELEASE.md
        draft: false
        prerelease: false
        name: ${{ steps.tag_bump_version.outputs.new_tag }}
        tag_name: ${{ steps.tag_bump_version.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
